import Head from "next/head";
import Link from "next/link";
import React from "react";
import styles from "../styles/Home.module.css";

import dynamic from "next/dynamic";

const Constitucion = dynamic(() => import("../components/Constitucion"), {
  ssr: false,
});

const Indice = dynamic(() => import("../components/Indice"), {
  ssr: false,
});

export async function getStaticProps(ctx) {
  return {
    props: {},
  };
}

export default function Home({}) {
  return (
    <>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>CPR 2022</h1>
          <Indice />
          <Constitucion />
        </main>
      </div>
    </>
  );
}
